### ISSUE TITLE
image grows from top-left, not center like animation in README

### ISSUE THREAD

**Issue by 0-M** [hiragram/YHImageViewer#10]
When clicking a YHImageViewer, it seems to zoom/grow to fit the screen from the top-left corner. When closing from a tap, it shrinks into the top-left again. 

I think the intended behavior is to grow in the center of the screen, then shrink into the center. This style is shown in the README of this repo. Do I need to set some variable to center? 

Screenshot of this happening on close:

![ios simulator screen shot aug 29 2015 7 43 03 pm](https://cloud.githubusercontent.com/assets/3653307/9565019/45068014-4e86-11e5-8f4d-67027b4ef934.png)

**Comment by hiragram** [comment]
@mmarkman I am sorry to delay responding.

>  it seems to zoom/grow to fit the screen from the top-left corner. 

Would you show me your code?
YHImageViewer uses frame of source UIImageView to decide start of animation.

Basic usage in readme is as follows:

```
func imageTapped(recognizer:UITapGestureRecognizer) {
    let imageViewer = YHImageViewer()
    imageViewer.backgroundColor = UIColor.blackColor()
    self.imageViewer = imageViewer
    // ^- This line is required. 
    // If imageViewer is referenced by nothing, 
    // it will be released immediately and window will not appear.
    imageViewer.show(sampleImageView)
}
```

When sampleImageView.frame is x:0, y:0, width:0, height:0 , the animation starts from top-left corner.

**Comment by hiragram** [comment]
Is your screenshot taken during animating, or after animation finished?
If animation finished like this picture, it is weired.

**Comment by 0-M** [comment]
@hiragram the screenshot was mid-animation, I was just showing that the image was animating into a corner.

my code:

``` swift

        // in viewDidLoad()


        var imageForDetail:UIImage!
        var imageViewForDetail:UIImageView!

        self.imageViewer = YHImageViewer()
        imageViewer.backgroundColor = UIColor.blackColor()

        // show loading indicator
        var loading = MBProgressHUD.showHUDAddedTo(self.view, animated: true)

        app.getImageFromURL(imageURL){
            image, success, code in

            // image loaded, hide loading indicator
            loading.hide(true)

            if success {

                imageForDetail = image
                imageViewForDetail = UIImageView(image: imageForDetail)

                // this off-center issue (#10) existed before I added completion,
                // PR for completion feature coming soon
                self.imageViewer.show(imageViewForDetail, completion: {
                    self.navigationController?.popViewControllerAnimated(false)
                })

            } else {
                self.navigationController?.popViewControllerAnimated(true)
            }
        }

```

**Comment by hiragram** [comment]
@mmarkman thanks.

When imageViewer.show() is called, has imageViewForDetail appeared on screen?

If it hasn't , imageView animating from / to top-left is correct behavior.
If you want imageViewForDetail to come from center of screen, you should set imageViewForDetail.frame to center of screen.

**Comment by 0-M** [comment]
thanks @hiragram I'll do that!

**Comment by hiragram** [comment]
@mmarkman If there were any problems, reopen this issue again :)
:+1:

**Comment by 0-M** [comment]
@hiragram I now have a better understanding of how this should work, and I think your readme/description could benefit from some re-phrasing. 

What YHImageViewer does: 

> "Make a UIImageView fullscreen, allow pinch to zoom, and flick/tap to dismiss."

I don't display my "detail" UIImageView on screen before using it because I'm loading a high-resolution version of the image to display. I already have a low-res version of the image, but I don't want the low-res image to get zoomed.

That said, I could use the low-res UIImageView and replace imageView.image with the high-res one when it finishes loading.
