### ISSUE TITLE
Re-use YHImageViewer

### ISSUE THREAD

**Issue by 0-M** [hiragram/YHImageViewer#3]
Would be convenient if I could click, see the detail, flick away, and **REPEAT**.

**Comment by 0-M** [comment]
oops, was an issue with my use. it's totally reusable. my bad

**Comment by hiragram** [comment]
@mmarkman Thank you for your comment.
YHImageViewer is my very first OSS product so I'm glad that you are interested in it.
Any issue/comment/guidance are welcome :)

**Comment by hiragram** [comment]
@mmarkman By the way, I want to know how you found YHImageViewer.
It is not published on cocoacontrols.com yet, and had only one star (It's mine).

**Comment by 0-M** [comment]
@hiragram I found it on the cocoapods web site, it's exactly what I need. I'm launching the viewer from a UITableViewCell, so I couldn't (easily) access the UIViewController to set a delegate (which is required by other similar libraries).

Can't wait for zooming, I really need that functionality. Thanks for making this!

**Comment by hiragram** [comment]
@mmarkman I see.
Zooming and some other features are work-in-progress.
I am going to release next minor version includes zooming this weekend.
If you have any request or idea, please write an issue. :smile:

Would you tell me the name of 

> (which is required by other similar libraries)

for my reference?

**Comment by 0-M** [comment]
@hiragram I was trying MWPhotoBrowser and NYTPhotoViewer, both of which required reference of a UIViewController. 

If you can continue to make yours easy to drop into a UIView subtype, I'll continue using it!

**Comment by hiragram** [comment]
:+1: :+1: :+1: :+1: :+1:
